### ISSUE TITLE
Define custom touch areas.

### ISSUE THREAD

**Issue by pixelwave** [buglloc/esphome-components#5]
Hi Andrew,

I followed your work regarding the T-Display S3 Long.

I got the screen working with your example: https://ut.buglloc.com/iot/esphome/t-display-s3-long-esphome/

What I am struggling with is to setup a binary_sensor to define a custom touch area.

In the ESPHome documentation it says:

```
binary_sensor:
  - platform: touchscreen
    name: Top Left Touch Button
    x_min: 0
    x_max: 100
    y_min: 0
    y_max: 100
    page_id: home_page_id
```

But somehow that is not compatible with your custom component or I am doing something wrong?

Help would be greatly appreciated.

**Comment by pixelwave** [comment]
Never mind ... I cleaned the build files in esphome, recompiled and now it works with:

```
binary_sensor:
  - platform: touchscreen
    name: Top Left Touch Button
    #id: touch_key0
    x_min: 0
    x_max: 100
    y_min: 0
    y_max: 100
    #page_id: home_page_id
    on_press:
    - logger.log: "Key0 was touched"
```

Thanks for your great contribution making this display work!
